### ISSUE TITLE
i can't "go get" successfully.

### ISSUE THREAD

**Issue by briteming** [awnumar/rosen#9]
hi.

in my linux vps.
[root@racknerd-7b97d8 gopath]# go version
go version go1.16 linux/amd64
[root@racknerd-7b97d8 gopath]# go get -u -v github.com/awnumar/rosen/
go get github.com/awnumar/rosen: no matching versions for query "upgrade"
[root@racknerd-7b97d8 gopath]#

how to fix it?

**Comment by awnumar** [comment]
Hey, sorry for the delay. I have updated the installation instructions, let me know if they work for you.
